version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sunpower-sqs-to-dynamodb"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-w5b2hfr6gpv2"
s3_prefix = "sunpower-sqs-to-dynamodb"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
